spring:
  datasource:
    url: jdbc:h2:mem:sudokumind;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;INIT=CREATE DOMAIN IF NOT EXISTS JSONB AS JSON
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: local-google-client-id
            client-secret: local-google-client-secret

app:
  frontend-url: ${FRONTEND_URL:http://localhost:3100}
